.swiftlint.yml, Sources/NostrSDK/RelayMessage.swift, Sources/NostrSDK/RelayResponse.swift, Tests/NostrSDKTests/Fixtures/auth_challenge.json, Tests/NostrSDKTests/Fixtures/count_response.json, Tests/NostrSDKTests/Fixtures/eose.json, Tests/NostrSDKTests/Fixtures/event.json, Tests/NostrSDKTests/Fixtures/notice.json, Tests/NostrSDKTests/Fixtures/ok_fail_reason.json, Tests/NostrSDKTests/Fixtures/ok_success.json, Tests/NostrSDKTests/Fixtures/ok_success_reason.json, Tests/NostrSDKTests/RelayMessageDecodingTests.swift
Adding parsing for relay response messages: `NOTICE`, `OK`, `EOSE`, `COUNT`, `AUTH`, and `EVENT`
Ignoring `identifier_name` SwiftLint rule so we can have the `.ok` enum case
=> relay response message parsing and tests

Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/FixtureLoading.swift, Tests/NostrSDKTests/RelayMessageDecodingTests.swift
This PR converts `FixtureLoader` to a protocol extension `FixtureLoading` and makes its function throw for simpler call sites. It illustrates how lightweight and simple a protocol extension is and when it can be used to replace a class.
=> convert FixtureLoader to a protocol extension FixtureLoading, make function throw for simpler call sites

Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/FixtureLoading.swift
This PR simplifies `decodeFixture`. Since we are already in a throwing context, there's no need to use `do-catch`. And we can pass the generic type in by specifying the type of the return parameter at the call site rather than as a parameter into the function.
=> simplify decodeFixture

.swiftlint.yml, Sources/NostrSDK/RelayInfo.swift, Tests/NostrSDKTests/Fixtures/relay_info.json, Tests/NostrSDKTests/RelayInfoTests.swift
This PR adds support for NIP-11 Relay Information Document decoding. These properties will give clients all the necessary information a relay offers about its service.
=> add support and test for NIP-11 Relay Information Document

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/EventSerializer.swift, Sources/NostrSDK/EventVerifying.swift, Sources/NostrSDK/NostrEvent.swift, Sources/NostrSDK/Relay.swift, Sources/NostrSDK/SignatureVerifying.swift, Tests/NostrSDKTests/ContentSigningTests.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventSerializationTests.swift, Tests/NostrSDKTests/EventVerifyingTests.swift, Tests/NostrSDKTests/Helpers/Keypair+Test.swift
This PR adds code for calculating the identifier of an event from its json serialization (defined in NIP-01), verifying the event id and signature, and publishing an event to a relay.
=> add ability to create events, sign them, and send them to a relay

Sources/NostrSDK/Events/ContactListEvent.swift, Sources/NostrSDK/RelayResponse.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/contact_list_with_relays.json
Adds the ContactListEvent and unit tests for parsing them. In particular, please check out how I marked the relays as deprecated.
Closes #52
=> added ContactListEvent and tests

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/ReactionEvent.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/reaction.json
https://github.com/nostr-protocol/nips/blob/master/25.md
This implementation is missing custom emoji reactions, but I want to handle that in a separate PR because custom emojis can be used in other places outside of reactions.
https://github.com/nostr-protocol/nips/blob/master/25.md#custom-emoji-reaction
=> Add NIP-25 reactions

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Filter.swift, Sources/NostrSDK/Keys.swift, Tests/NostrSDKTests/KeysTests.swift, demo/NostrSDKDemo.xcodeproj/project.pbxproj, demo/NostrSDKDemo/ContentView.swift, demo/NostrSDKDemo/Demo Views/DirectMessageDemoView.swift, demo/NostrSDKDemo/Demo Views/QueryRelayDemoView.swift, demo/NostrSDKDemo/Helpers/Helpers.swift, demo/NostrSDKDemo/Views/ConnectRelayView.swift, demo/NostrSDKDemo/Views/KeyInputSectionView.swift, demo/NostrSDKDemo/Views/RelayFormView.swift
=> Add Demo of Sending Direct Message

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/ContactListEvent.swift, Tests/NostrSDKTests/EventCreatingTests.swift
Adds the ability to create contact lists from a list of pubkeys or pubkey tags. I provided both options so it can be very simple if the client prefers, but it also has full functionality matching the spec (for petnames).
=> add contact list creation and tests

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/DirectMessageEvent.swift, Sources/NostrSDK/Events/ReactionEvent.swift, Sources/NostrSDK/Events/RecommendServerEvent.swift, Sources/NostrSDK/Events/SetMetadataEvent.swift, Sources/NostrSDK/Events/TextNoteEvent.swift
Implements the idea from https://github.com/nostr-sdk/nostr-sdk-ios/pull/75 where we want to prevent disparities between the `NostrEvent` subclass and it's `kind` property.
=> preclude NostrEvent subclasses from using the initializer that allows specifying the kind explicitly

Sources/NostrSDK/Events/SetMetadataEvent.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/set_metadata_alternate.json
I came across a situation where I was running into a lot of `nil` `UserMetadata` objects. It turns out if the website field is empty (same goes for picture and banner picture) or an invalid URL the whole decoding process fails instead of just setting that one property to `nil`. I used a decoder in order to set only those fields to `nil` instead or failing to decode at all.
=> Handle Invalid URLs when Parsing UserMetadata

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/DeletionEvent.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/Fixtures/text_note_deletable.json
Note: This does not include the ability to delete parameterized replaceable events, because we have not yet added them to the SDK.
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/94
=> add DeletionEvent

.swiftlint.yml, Sources/NostrSDK/Bech32.swift, Sources/NostrSDK/Helpers/String+Additions.swift, Sources/NostrSDK/MetadataCoding.swift, Tests/NostrSDKTests/Bech32Tests.swift, Tests/NostrSDKTests/MetadataCodingTests.swift
See NIP-19:
https://github.com/nostr-protocol/nips/blob/master/19.md
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/112
=> add support for Bech32-encoded, TLV-encoded identifiers (nprofile, nevent, nrelay, naddr)

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/Calendars/DateBasedCalendarEvent.swift, Sources/NostrSDK/Events/Calendars/TimeBasedCalendarEvent.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/LongformContentEvent.swift, Sources/NostrSDK/Events/MuteListEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/mute_list.json
Implements the first NIP-51 list event: a kind 10000 MuteListEvent.
https://github.com/nostr-protocol/nips/blob/master/51.md#standard-lists
Other list types will follow in a subsequent PR.
=> add support for NIP-51 mute lists

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/Calendars/CalendarEventParticipant.swift, Sources/NostrSDK/Events/ContactListEvent.swift, Sources/NostrSDK/Events/DeletionEvent.swift, Sources/NostrSDK/Events/Tags/HashtagInterpreting.swift, Sources/NostrSDK/Events/Tags/ReferenceTagInterpreting.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/Calendars/CalendarEventParticipantTests.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/RelayRequestEncodingTests.swift
We can now optionally use shorthand functions for creating tags.
```swift
let tag = Tag.pubkey(<pubkey hex>)
let tags: [Tag] = [.pubkey(<pubkey hex>)]
```
I created these functions for tags that are used frequently, but more could be added. The regular initializer is unchanged and can still be used when desired.
=> Tags: add shorthand functions for easier usage and readability

Package.resolved, Package.swift, Sources/NostrSDK/Keys.swift, Sources/NostrSDK/NIP44v2Encrypting.swift, Tests/NostrSDKTests/FixtureLoading.swift, Tests/NostrSDKTests/Fixtures/nip44.vectors.json, Tests/NostrSDKTests/KeysTests.swift, Tests/NostrSDKTests/NIP44Vectors.swift, Tests/NostrSDKTests/NIP44v2EncryptingTests.swift, demo/NostrSDKDemo/Demo Views/DirectMessageDemoView.swift
NIP-44 v2: https://github.com/nostr-protocol/nips/blob/4b79bc67c471f77061d62704538e5fdd6ac28ae8/44.md
Heavily inspired by this Kotlin implementation from @vitorpamplona
https://github.com/paulmillr/nip44/tree/b60eef26fe336e7e086b98a1bad27f0b8f09bca2/kotlin
=> Add support for NIP-44 v2 encryption

Package.resolved, Package.swift, Sources/NostrSDK/NIP44v2Encrypting.swift
Using `Sodium`, which is backed by a C library, broke documentation generation for some reason. We were using it for the `ChaCha20` cipher for NIP-44 encryption, introduced in this commit: https://github.com/nostr-sdk/nostr-sdk-ios/commit/f1384b7a447a3d16cf97a93141d8a2001e884c74
This PR replaces `Sodium` with `CryptoSwift`, a pure Swift library, which implements the ChaCha20 cipher and seems to fix documentation generation. I tried it both locally and on the `main` remote branch on my fork.
The fact that `NIP44v2EncryptingTests` passes gives me confidence that the `CryptoSwift` usage is functionally equivalent to what we were doing with `Sodium`.
=> Replace Sodium with CryptoSwift

CONTRIBUTING.md, README.md
Added missing acknowledgements and their respective open-source licenses.
I also think that we can probably open up contributions if anyone would like to at this point.
=> Update readme and contributing guides

Tests/NostrSDKTests/Events/DeletionEventTests.swift, Tests/NostrSDKTests/Fixtures/deletion.json
All the other NostrEvents have tests for creating and decoding events. The only test that's missing is this one.
=> Add a test for decoding a deletion event

Sources/NostrSDK/CustomEmoji.swift, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/Calendars/CalendarEventParticipant.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/Tags/EventCoordinates.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/Events/NostrEventTests.swift
This change enables NostrEvent and its subclasses to be hashable, which is great for allowing indexing and deduplicating in Set and Dictionary data structures.
This change also prevents events with the same `id` from being erroneously equated the same as another event with the same `id` if any of its other properties are different. Note that this is a breaking change.
=> Make NostrEvent conform to the Hashable protocol and change its Equatable implementation to compare against all its properties

.github/workflows/unit.yml, README.md
I suspect there was a breaking change with GitHub's `macos` runner, which caused it to not recognize Swift 5.7. Let's just bump the minimum supported Swift version to 5.8. I also added 5.10 to the test matrix.
=> Fix build by increasing minimum Swift version to 5.8

Sources/NostrSDK/Events/BookmarksListEvent.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/GiftWrap/GiftWrapEvent.swift, Sources/NostrSDK/Events/GiftWrap/SealEvent.swift, Sources/NostrSDK/Events/MetadataEvent.swift, Sources/NostrSDK/Events/MuteListEvent.swift, Sources/NostrSDK/Events/TextNoteRepostEvent.swift, Sources/NostrSDK/LegacyDirectMessageEncrypting.swift, Sources/NostrSDK/NIP44v2Encrypting.swift, Sources/NostrSDK/WebSocket.swift
I noticed unrelated SwiftLint errors come up on one of my other development branches. I then [re-ran](https://github.com/nostr-sdk/nostr-sdk-ios/actions/runs/9285404857) the SwiftLint CI build on the `main` branch and the same errors came up. I'm guessing that we're automatically pulling in a new SwiftLint version or configuration in CI somehow.
Indeed, after updating swiftlint locally using `brew install swiftlint`, I was able to locally reproduce the lint errors.
This pull request fixes the new lint errors.
=> Fix SwiftLint errors

.github/workflows/docs.yml, .github/workflows/swiftlint.yml, .github/workflows/unit.yml, Sources/NostrSDK/Events/BookmarksListEvent.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/GiftWrap/GiftWrapEvent.swift, Sources/NostrSDK/Events/GiftWrap/SealEvent.swift, Sources/NostrSDK/Events/MetadataEvent.swift, Sources/NostrSDK/Events/MuteListEvent.swift, Sources/NostrSDK/Events/TextNoteRepostEvent.swift, Sources/NostrSDK/LegacyDirectMessageEncrypting.swift, Sources/NostrSDK/NIP44v2Encrypting.swift, Sources/NostrSDK/WebSocket.swift
Older versions of Checkout use deprecated Node.js versions.
We were getting these kinds of warnings in the build:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
`The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`
Upgrading to Checkout V4 fixes these warnings.
=> Upgrade GitHub Actions Checkout to V4 to fix Node.js deprecation warnings

README.md, Sources/NostrSDK/Bech32IdentifierType.swift, Sources/NostrSDK/Events/AuthenticationEvent.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/NonParameterizedReplaceableEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/ParameterizedReplaceableEvent.swift, Sources/NostrSDK/Events/ReplaceableEvent.swift, Sources/NostrSDK/Keys.swift, Sources/NostrSDK/MetadataCoding.swift, Tests/NostrSDKTests/Events/NonParameterizedReplaceableEventTests.swift, Tests/NostrSDKTests/Events/NostrEventTests.swift, Tests/NostrSDKTests/Events/ParameterizedReplaceableEventTests.swift, Tests/NostrSDKTests/MetadataCodingTests.swift
https://github.com/nostr-protocol/nips/blob/master/19.md
This change enables clients to generate shareable identifiers easily for human consumption.
I also refactored the `npub` and `nsec` bech32 prefixes into the `Bech32IdentifierType` enum.
=> Add NIP-19 bech32 identifier generation for note, nevent, and naddr prefixes

Sources/NostrSDK/Tag.swift
Clients need to access these Tag properties because referring to tag values are an essential part of the fundamental Nostr data structures.
=> Make properties of Tag public

Sources/NostrSDK/Filter.swift
- Prefix filters are not allowed anymore
- Clarifying that timestamp filters are inclusive, not exclusive (see https://github.com/nostr-protocol/nips/pull/1349)
I'm planning on creating a separate PR to add more `guard` checks in the initializer to make it harder for developers to do the wrong thing.
=> Fix comments on Filter to reflect the current state of NIP-01

.github/workflows/swiftlint.yml, .github/workflows/unit.yml
As an example, I could not properly merge https://github.com/nostr-sdk/nostr-sdk-ios/pull/171 because the workflows were not running. I had to temporarily remove the merge restrictions to move ahead.
=> Fix GitHub workflows to trigger on pull_request_target so that they can run on PRs from public forks

Sources/NostrSDK/RelayResponse.swift
This change is necessary to allow clients to implement their own relay response handling strategies.
=> Expose RelayResponse.Message and RelayResponse.MessagePrefix as public

Sources/NostrSDK/CustomEmoji.swift, Sources/NostrSDK/Events/AuthenticationEvent.swift, Sources/NostrSDK/Events/BookmarksListEvent.swift, Sources/NostrSDK/Events/Calendars/CalendarEventRSVP.swift, Sources/NostrSDK/Events/Calendars/CalendarListEvent.swift, Sources/NostrSDK/Events/Calendars/DateBasedCalendarEvent.swift, Sources/NostrSDK/Events/Calendars/TimeBasedCalendarEvent.swift, Sources/NostrSDK/Events/DeletionEvent.swift, Sources/NostrSDK/Events/FollowListEvent.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/GiftWrap/GiftWrapEvent.swift, Sources/NostrSDK/Events/GiftWrap/SealEvent.swift, Sources/NostrSDK/Events/LegacyEncryptedDirectMessageEvent.swift, Sources/NostrSDK/Events/LongformContentEvent.swift, Sources/NostrSDK/Events/MetadataEvent.swift, Sources/NostrSDK/Events/MuteListEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/ReactionEvent.swift, Sources/NostrSDK/Events/RelayListMetadataEvent.swift, Sources/NostrSDK/Events/ReportEvent.swift, Sources/NostrSDK/Events/Tags/EventTag.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Tests/NostrSDKTests/Events/GiftWrap/GiftWrapEventTests.swift, Tests/NostrSDKTests/Events/GiftWrap/RumorEventTests.swift, Tests/NostrSDKTests/Events/GiftWrap/SealEventTests.swift, Tests/NostrSDKTests/Events/MetadataEventTests.swift, Tests/NostrSDKTests/Events/ReactionEventTests.swift, Tests/NostrSDKTests/Events/TextNoteEventTests.swift
https://github.com/nostr-sdk/nostr-sdk-ios/issues/170
This PR uses a combination of different patterns (builder, inheritance, protocols, generics) to enable what I think is a flexible, powerful, easy-to-use framework to build NostrEvents.
It allows maintainers of the SDK to compose shared logic / components together, e.g. NIPs that are used in multiple event kinds. Duplicate code no longer needs to be copied into multiple `EventCreating` functions.
It allows developers using the SDK to build NostrEvents of any event kind, even if it is not yet supported in the SDK. They can make additions on top of what the SDK provides, or construct their own custom event. They can also not be constrained to what I believe in my opinion is a rigid `EventCreating` protocol API, where they need to pass in …
=> Add NostrEventBuilding protocol to enable flexible composition of shared patterns across different kinds of NostrEvents

Sources/NostrSDK/Events/AuthenticationEvent.swift, Tests/NostrSDKTests/Events/AuthenticationEventTests.swift
https://github.com/nostr-sdk/nostr-sdk-ios/issues/170
=> Add AuthenticationEvent.Builder to deprecate equivalent function in EventCreating

Sources/NostrSDK/Events/GiftWrap/GiftWrapEvent.swift, Tests/NostrSDKTests/Events/GiftWrap/GiftWrapEventTests.swift
This should be a backwards compatible change.
=> Add support for receiver aliases for gift wrap creation to avoid exposing identities and improve test coverage

Sources/NostrSDK/Events/BookmarksListEvent.swift, Sources/NostrSDK/Events/Calendars/CalendarEventRSVP.swift, Sources/NostrSDK/Events/Calendars/CalendarListEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/Tags/EventCoordinates.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Tests/NostrSDKTests/Events/DeletionEventTests.swift
This PR deprecates the `EventCoordinatesTagInterpreting` protocol because:
1. [NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md#tags) says that all event kinds can refer to addressable or replaceable events (i.e. reference event coordinates). I've added `referencedEventCoordinates` to `NostrEvent`.
2. It's unclear what `eventCoordinates` means. Is it referring to the coordinates of the event object itself or events it's referencing? (it's the latter)
[NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md#tags) also says that all event kinds can refer to other events or users, so I've added `referencedPubkeys` and `referencedEventIds` to `NostrEvent`.
=> Add referencedPubkeys, referencedEventIds, and referencedEventCoordinates to NostrEvent

README.md, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/Events/NostrEventTests.swift, Tests/NostrSDKTests/Fixtures/test_event_expired.json
https://github.com/nostr-protocol/nips/blob/master/40.md
=> Add support for NIP-40 - Expiration Timestamp

README.md, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/LabelEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/Tags/PubkeyTag.swift, Tests/NostrSDKTests/Events/LabelEventTests.swift, Tests/NostrSDKTests/Events/NostrEventTests.swift
https://github.com/nostr-protocol/nips/blob/master/32.md
=> Add support for NIP-32 Labeling

demo/NostrSDKDemo.xcodeproj/project.pbxproj, demo/NostrSDKDemo/ContentView.swift, demo/NostrSDKDemo/Demo Views/DecryptMessageDemoView.swift, demo/NostrSDKDemo/Demo Views/EncryptMessageDemoView.swift
I added an example for encrypting/decrypting with nip44 to the demo project, I was using this myself to help me understand but might be useful for others too.
I copied the style from LegacyDirectMessageDemoView but limited it to encrypt/decrypt, no publishing to relays.
=> Add nip44 encrypt/decrypt example to demo project
