.github/workflows/swiftlint.yml, .github/workflows/unit.yml, .swiftlint.yml, Package.swift, README.md, Sources/NostrSDK/EventTag.swift, Sources/NostrSDK/NostrEvent.swift, Tests/NostrSDKTests/EventDecodingTests.swift
- Add SwiftLint workflow
- Add Unit test workflow
- Add badges to README
=> Add SwiftLint and Unit Test Workflow

.github/workflows/unit.yml, Package.swift, Sources/NostrSDK/WebSocket.swift
Also had to set minimum versions to use this WebSocket API:
- macOS 13
- iOS 16
=> Add WebSocket.swift from Damus (permission was given)

Sources/NostrSDK/Filter.swift, Sources/NostrSDK/RelayRequest.swift, Sources/NostrSDK/WebSocket.swift, Tests/NostrSDKTests/FilterEncodingTests.swift, Tests/NostrSDKTests/Fixtures/filter_all_fields.json, Tests/NostrSDKTests/RelayRequestEncodingTests.swift
This PR makes some small changes to foundational components of the SDK that I wanted to do before building the relay connection. No functional changes are intended.
=> minor tweaks to foundational components

Sources/NostrSDK/Filter.swift, Sources/NostrSDK/Relay.swift, Sources/NostrSDK/WebSocket.swift, Tests/NostrSDKTests/RelayTests.swift
This PR adds the communication interface to relays.
* Connect to a relay
* Create a subscription based on a provided `Filter`
* Easily listen for and respond to events and state changes
=> add Relay, provides the communication interface to relays

.github/workflows/unit.yml, Sources/NostrSDK/Relay.swift, Tests/NostrSDKTests/RelayTests.swift
=> add optional delegate interface for receiving state changes and events from Relay

Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Filter.swift, Sources/NostrSDK/NostrEvent.swift, Sources/NostrSDK/Tag.swift
No functional changes intended
=> add a bunch of documentation

Sources/NostrSDK/DataRequesting.swift, Sources/NostrSDK/NIP05Validating.swift, Tests/NostrSDKTests/NIP05ValidationTests.swift
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/33
=> add NIP-05 validation

Sources/NostrSDK/ContentSigning.swift, Sources/NostrSDK/Data+Additions.swift, Sources/NostrSDK/Helpers/String+Additions.swift, Sources/NostrSDK/NostrEvent.swift, Sources/NostrSDK/SignatureVerifying.swift, Tests/NostrSDKTests/ContentSigningTests.swift, Tests/NostrSDKTests/EventSerializationTests.swift, Tests/NostrSDKTests/EventVerifyingTests.swift, Tests/NostrSDKTests/Fixtures/simple_note.json, Tests/NostrSDKTests/Fixtures/test_event.json
This PR adds functions, tests, and documentation for signing content with a private key and for verifying such signatures.
=> add signing and signature verification

demo/NostrSDKDemo.xcodeproj/project.pbxproj, demo/NostrSDKDemo.xcodeproj/project.xcworkspace/contents.xcworkspacedata, demo/NostrSDKDemo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, demo/NostrSDKDemo/Assets.xcassets/AccentColor.colorset/Contents.json, demo/NostrSDKDemo/Assets.xcassets/AppIcon.appiconset/Contents.json, demo/NostrSDKDemo/Assets.xcassets/Contents.json, demo/NostrSDKDemo/ConnectRelayView.swift, demo/NostrSDKDemo/ContentView.swift, demo/NostrSDKDemo/GenerateKeyView.swift, demo/NostrSDKDemo/ListOptionView.swift, demo/NostrSDKDemo/NIP05VerificationView.swift, demo/NostrSDKDemo/NostrSDKDemoApp.swift, demo/NostrSDKDemo/Preview Content/Preview Assets.xcassets/Contents.json, demo/NostrSDKDemo/QueryRelayView.swift, demo/Package.swift
Moves demo app project into `/demo` and uses the local `NostrSDK` package instead of downloading from GitHub.
#53
=> Move Demo App into Repo

Sources/NostrSDK/EventKind.swift
Inspired by this StackOverflow answer: https://stackoverflow.com/a/61150450
=> Expand EventKind enum to support unknown event kind numbers

Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/GenericRepostEvent.swift, Sources/NostrSDK/Events/TextNoteRepostEvent.swift, Sources/NostrSDK/RelayResponse.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/generic_repost.json
This PR adds NostrEvent subclasses for both repost types.
=> add types: TextNoteRepostEvent (kind 6) and GenericRepostEvent (kind 16)

demo/NostrSDKDemo.xcodeproj/project.pbxproj, demo/NostrSDKDemo/ContentView.swift, demo/NostrSDKDemo/Demo Views/ConnectRelayDemoView.swift, demo/NostrSDKDemo/Demo Views/GenerateKeyDemoView.swift, demo/NostrSDKDemo/Demo Views/NIP05VerificationDemoView.swift, demo/NostrSDKDemo/Demo Views/QueryRelayDemoView.swift, demo/NostrSDKDemo/Helpers/Helpers.swift, demo/NostrSDKDemo/Views/ConnectRelayView.swift, demo/NostrSDKDemo/Views/ListOptionView.swift
Updated the demo app to organize the views better and be able to share a relay connection:
=> Refactor Demo App

demo/NostrSDKDemo/Demo Views/QueryRelayDemoView.swift
This PR improves readability and usability of the Query Relay view in the Demo App.
* move functional logic out of the view into a separate function and break things up a bit
* remove an unused property
* allow not setting the author pubkey so you can filter just the kind
* close the previous subscription and re-subscribe when user changes the pubkey or the kind
=> Demo App: improvements to Query Relay view

demo/NostrSDKDemo/Views/ConnectRelayView.swift
=> Auto-Connect to Relay on Start

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/text_note_subject.json
https://github.com/nostr-protocol/nips/blob/master/14.md
=> add subject tag for text note events and tests (covers NIP-14)

Sources/NostrSDK/RelayResponse.swift, Tests/NostrSDKTests/RelayResponseDecodingTests.swift
defined in NIP-01
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/85
=> add support for relay OK messages

Sources/NostrSDK/CustomEmoji.swift, Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/ReactionEvent.swift, Sources/NostrSDK/Events/SetMetadataEvent.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/CustomEmojiTests.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/custom_emoji_reaction.json, Tests/NostrSDKTests/Fixtures/set_metadata_custom_emojis.json, Tests/NostrSDKTests/Fixtures/text_note_custom_emoji.json
https://github.com/nostr-sdk/nostr-sdk-ios/issues/103
=> Add support for NIP-30 Custom Emojis

Sources/NostrSDK/Relay.swift, Sources/NostrSDK/WebSocket.swift, Tests/NostrSDKTests/RelayTests.swift
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/80
=> expose Relay URL publicly

Sources/NostrSDK/Keys.swift, Sources/NostrSDK/Loggers.swift, Sources/NostrSDK/RelayResponse.swift
Closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/77
=> migrate print() statements to Logger

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/BookmarksListEvent.swift, Sources/NostrSDK/Events/DeletionEvent.swift, Sources/NostrSDK/Events/FollowListEvent.swift, Sources/NostrSDK/Events/MuteListEvent.swift, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Events/Tags/EventTag.swift, Sources/NostrSDK/Events/Tags/HashtagInterpreting.swift, Sources/NostrSDK/Events/Tags/ReferenceTagInterpreting.swift, Sources/NostrSDK/Events/TextNoteEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/EventCreatingTests.swift, Tests/NostrSDKTests/EventDecodingTests.swift, Tests/NostrSDKTests/Fixtures/text_note_reply.json, Tests/NostrSDKTests/Fixtures/text_note_reply_deprecated_positional_tags.json, Tests/NostrSDKTests/Fixtures/text_note_root_reply.json, Tests/NostrSDKTests/Fixtures/text_note_root_reply_deprecated_positional_tags.json
https://github.com/nostr-protocol/nips/blob/master/10.md
=> Add NIP-10 support for e and p tags in kind 1 text events

Sources/NostrSDK/EventCreating.swift, Sources/NostrSDK/Events/Calendars/CalendarEventRSVP.swift, Tests/NostrSDKTests/Fixtures/calendar_event_rsvp.json
Reflects the changes from this merged PR in the NIPs repo: https://github.com/nostr-protocol/nips/pull/980
=> Remove label cruft in NIP-52 to reflect changes to spec

Sources/NostrSDK/WebSocket.swift
closes https://github.com/nostr-sdk/nostr-sdk-ios/issues/61
=> add documentation to WebSocket class

Sources/NostrSDK/RelayPool.swift, demo/NostrSDKDemo/Demo Views/DirectMessageDemoView.swift
Fixes https://github.com/nostr-sdk/nostr-sdk-ios/issues/142
=> Fix demo app to not crash when removing relays

demo/NostrSDKDemo.xcodeproj/project.pbxproj, demo/NostrSDKDemo/Demo Views/QueryRelayDemoView.swift
We should add a CI step to verify that the demo app can build to prevent this type of issue from happening in the future.
=> Fix compilation errors in demo app

Package.resolved, Package.swift, README.md, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/RelayListMetadataEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/Events/RelayListMetadataEventTests.swift, Tests/NostrSDKTests/Fixtures/relay_list_metadata.json, Tests/NostrSDKTests/Fixtures/relay_list_metadata_invalid_tags.json
[NIP-65 Relay List Metadata](https://github.com/nostr-protocol/nips/blob/master/65.md)
=> Add support for NIP-65 Relay List Metadata

Sources/NostrSDK/Events/ReactionEvent.swift, Tests/NostrSDKTests/Events/ReactionEventTests.swift
https://github.com/nostr-sdk/nostr-sdk-ios/issues/170
=> Add ReactionEvent.Builder to deprecate equivalent function in EventCreating

README.md, Sources/NostrSDK/Events/NostrEvent.swift, Sources/NostrSDK/Tag.swift, Tests/NostrSDKTests/Events/NostrEventTests.swift, Tests/NostrSDKTests/Fixtures/custom_event_alt_tag.json
https://github.com/nostr-protocol/nips/blob/master/31.md
=> Add support for NIP-31 alt tags

Sources/NostrSDK/RelayInfo.swift, Tests/NostrSDKTests/Fixtures/relay_info.json, Tests/NostrSDKTests/RelayInfoTests.swift
https://github.com/nostr-protocol/nips/blob/f3244a0903b1fedbd8aa89596c658c9529e19ea6/11.md
=> Update RelayInfo to reflect current NIP-11 specification

README.md, Sources/NostrSDK/EventKind.swift, Sources/NostrSDK/Events/AddressableEvent.swift, Sources/NostrSDK/Events/DraftPrivateWrapEvent.swift, Sources/NostrSDK/Events/PrivateEventRelayListEvent.swift, Tests/NostrSDKTests/Events/DraftPrivateWrapEventTests.swift, Tests/NostrSDKTests/Events/PrivateEventRelayListEventTests.swift
https://github.com/nostr-protocol/nips/blob/c88d9256135e53136ea2ce4f99b7e9cfcb21d143/37.md
=> Add NIP-37 support for draft events and private event relay list events
